# Redirección HTTP -> HTTPS
# Redirección HTTP -> HTTPS (al puerto 8443 del host)
server {
    listen 80;
    server_name _;

    return 301 https://localhost:8443$request_uri;
}

# Servidor HTTPS con proxy hacia Flask
server {
    listen 443 ssl;
    server_name _;

    # Certificado self-signed
    ssl_certificate     /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Aquí proxy-pass hacia el contenedor de la app
    location / {
        proxy_pass http://web:5000;

        # Encabezados recomendados
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
